name: "publishtestresults-action"
description: "Publish test results to Azure DevOps Test Store"
inputs:
  testResultsFormat:
    description: "Test Results Format"
    required: true
    default: "JUnit"
  testResultsFiles:
    description: "Test Results Files"
    required: true
    default: "**/TEST-*.xml"
  searchFolder:
    description: "Search Folder"
    required: false
    default: "${{ github.workspace }}"
  mergeTestResults:
    description: "Merge Test Results"
    required: false
    default: false
  testRunTitle:
    description: "Test Run Title"
    required: false
    default: "GitHub-PTR"
  failTaskOnFailedTests:
    description: "Fail Task On Failed Tests"
    required: false
    default: false
  failTaskOnMissingResultsFile:
    description: "Fail Task On Missing Results File"
    required: false
    default: false
  publishRunAttachments:
    description: "Upload logs and other files containing diagnostic information collected when the tests were run."
    required: false
    default: false
  adoOrganizationName:
    description: "Organization in ADO where the test results will be uploaded"
    required: true
  adoProjectName:
    description: "Project in a given ADO org where the test results will be uploaded"
    required: true
    

runs:
  using: "node20"
  main: "dist/index.js"